New-Alias cohh "C:\personal\git\streams\cohh.ps1"
New-Alias aftermath "C:\personal\git\streams\aftermath.ps1"
New-Alias ti "C:\personal\git\streams\ti.ps1"
New-Alias ti2 "C:\personal\git\streams\ti2.ps1"
#New-Alias phone "C:\Black_River\Git\scripts\phone.ps1"
